require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

# I keep the length as short as possible without having too much pain.
# 80 is too much pain, but many disagree.
Layout/LineLength:
  Max: 100

# Tests and Rake tasks may have long blocks.
Metrics/BlockLength:
  Exclude:
    - '**/Rakefile'
    - '**/spec/**/*_spec.rb'
    - '**/test/**/*_test.rb'

Metrics/ClassLength:
  Exclude:
    - '**/test/**/*_test.rb'
    - '**/test/**/test_*.rb'

# Mostly following https://robots.thoughtbot.com/lets-not
# which increases example length.
RSpec/ExampleLength:
  Enabled: false

# I may have PDF or otherwise graphics related specs
# that combine many expectations in one spec for rendering convenience.
RSpec/MultipleExpectations:
  Enabled: false
