inherit_from:
  - https://raw.githubusercontent.com/halo/dotfiles/master/dotfiles/rubocop.yml
  - https://raw.githubusercontent.com/halo/dotfiles/master/dotfiles/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.2
